import numpy as np


EPS_DIST = 5e-4
EPS_TIME = 5e-4

DV_MIN = 1e-10
DV_MAX = 1e10

COEF_OF_RESTITUTION = 0.90
DEFAULT_SPEED = 1.0
DEFAULT_DT_BASE =  1/20.0
DEFAULT_G = 1.0
MAX_STEPS_PER_FRAME = int(1/np.sqrt(DEFAULT_DT_BASE))
