
REMOVED             = 1
FIXED_VELOCITY      = 1 << 1
FIXED_POSITION      = 1 << 2
FIXED_MASS          = 1 << 3
FIXED_RADIUS        = 1 << 4
REPEL_ON_OVERLAP    = 1 << 5
BOUNCE_AS_PRIMARY   = 1 << 6
BOUNCE_AS_SECONDARY = 1 << 7
MERGE_AS_PRIMARY    = 1 << 8
MERGE_AS_SECONDARY  = 1 << 9

MERGE = MERGE_AS_PRIMARY|MERGE_AS_SECONDARY

BOUNCE = BOUNCE_AS_PRIMARY|BOUNCE_AS_SECONDARY

PRIMARY_BODY = FIXED_POSITION|FIXED_VELOCITY|FIXED_RADIUS|MERGE_AS_PRIMARY